---
title: "simulation"
author: ""
date: '`r Sys.Date()`'
output:
  html_document:
    highlight: py
    css: "style.css"
    code_folding: show
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options:
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  eval = T,
  echo = F,
  cache = T,
  fig.height = 12,
  fig.width = 24,
  out.width = '150%',
  warning = FALSE,
  message = F,
  include = T
)
library(rstan); library(tidyverse); library(knitr);library(ggforce);
library(cowplot)

library(grid)
library(gridExtra)

base_path <- rprojroot::find_rstudio_root_file()

# theme_set(theme_bw(base_size = 24))

library(tidyverse)
library(rstan)
# library(coda)
#
data_idx <- "0608"

total_res <- readRDS(paste0(base_path,"/","test/shinydata/", data_idx, "_data.rds"))
mpart <- readRDS(paste0(base_path,"/","test/shinydata/", data_idx, "_mpart.rds"))

rds_files <- fs::dir_ls(file.path(base_path, "test/outlier_check"))

outlierfiles <- str_subset(rds_files, "check/outlier_")
unbiasedfiles <- str_subset(rds_files, "unbiased_")
middlefiles <- str_subset(rds_files, "middle_")

a1 <- mpart %>%
  filter(str_detect(par_name,"lambda") ) %>%
  # filter(lvmodel != "rasch") %>%
  separate(cond,
           c("lvmodel","samplesize","nitem","r2y","r2eta","linearity","outdist","rep"), "_") %>%
  mutate(
    overest = err > 0,
    underest = err < 0,
    evenest  = err == 0
  )

a1 <- mpart %>%
  filter(str_detect(par_name,"lambda") ) %>%
  separate(cond,
           c("lvmodel","samplesize","nitem","r2y","r2eta","linearity","outdist","rep"), "_") %>%
  mutate(
    overest = err > 0,
    underest = err < 0,
    evenest  = err == 0
  ) %>%
  filter(!str_detect(lvmodel, "normal|logn|unif"))

outliers <- a1 %>%
  filter(err != 0) %>%
  # filter(lvmodel == invest_lvm) %>%
  # filter(samplesize == invest_ss, nitem == invest_ni) %>%
  select(lvmodel, samplesize, nitem, rep, par_name, err, true_param, mean, X2.5., X97.5., Rhat) %>%
  arrange(-abs(err)) %>%
  slice(1:10)


set.seed(1)
unbiased <- a1 %>%
  filter(err != 0) %>%
  select(lvmodel, samplesize, nitem, rep, par_name, err, true_param, mean, X2.5., X97.5., Rhat) %>%
  filter(abs(err) < 0.1 ) %>%
  sample_n(10)

set.seed(1)
middle <- a1 %>%
  filter(err != 0) %>%
  select(lvmodel, samplesize, nitem, rep, par_name, err, true_param, mean, X2.5., X97.5., Rhat) %>%
  filter(abs(err) < 0.5 & abs(err) > 0.1 ) %>%
  sample_n(10)
```


## Outliers results {.tabset}

### Table

```{r}
outliers %>% kable()
```

### trace plot

```{r, results = 'asis'}

for(i in 1:10) {
  o1 <- readRDS(outlierfiles[i])
  #### 
  cat("\n\n#### ", o1$cond, "\n\n")
  
  pp <- o1$p + labs(title = o1$cond) +
    theme(text = element_text(size = 40),
      plot.title = element_text(size = 40),
      axis.title = element_text(size = 40),
      legend.title = element_text(size = 40)
      )
  print(pp)
  
  cat('\n<div class = "row">',"\n\n")
  cat('\n<div class="column2-left">',"\n\n")
  
  cbind(true_v = o1$true_v, o1$est_v) %>% 
    data.frame() %>% 
    tibble(bias = o1$bias) %>% 
    select(true_v, mean, bias, sd, Rhat) %>% 
    mutate_all(round, 3) %>% 
    kable() %>% 
    print()
  cat('\n</div>',"\n\n")
  
  cat('\n<div class="column2-right">',"\n\n")
  
  o1$modelconver$autocr %>% 
    data.frame() %>% 
    setNames("autocorr") %>% 
    mutate_all(round, 3) %>% 
    kable() %>% 
    print()
  
  
  cat('\n</div>',"\n\n")
  cat('\n</div>',"\n\n")
  
  cat("\n\n")
  
}
```


## Unbiased results {.tabset}

### Table

```{r}
unbiased %>% kable()
```

### trace plot

```{r, results = 'asis'}

for(i in 1:10) {
  o1 <- readRDS(unbiasedfiles[i])
  
  cat("\n\n#### ", o1$cond, "\n\n")
  
  pp <- o1$p + labs(title = o1$cond) +
    theme(
      text = element_text(size = 40),
      plot.title = element_text(size = 40),
      axis.title = element_text(size = 40),
      legend.title = element_text(size = 40)
      )
  print(pp)
  
  cat('\n<div class = "row">',"\n\n")
  cat('\n<div class="column2-left">',"\n\n")
  
  cbind(true_v = o1$true_v, o1$est_v) %>% 
    data.frame() %>% 
    tibble(bias = o1$bias) %>% 
    select(true_v, mean, bias, sd, Rhat) %>% 
    mutate_all(round, 3) %>% 
    kable() %>% 
    print()
  cat('\n</div>',"\n\n")
  
  cat('\n<div class="column2-right">',"\n\n")
  
  o1$modelconver$autocr %>% 
    data.frame() %>% 
    setNames("autocorr") %>% 
    mutate_all(round, 3) %>% 
    kable() %>% 
    print()
  
  
  cat('\n</div>',"\n\n")
  cat('\n</div>',"\n\n")
  
  cat("\n\n")
  
}
```



## Figures


```{r}

# theme_set(
#   theme(
#       text = element_text(size = 40),
#       plot.title = element_text(size = 40),
#       axis.title = element_text(size = 40),
#       legend.title = element_text(size = 40)
#       )
# )

total_res1 <-
  total_res %>%
  mutate(
    par_name = as.character(par_name),
    par_name = case_when(
      str_detect(par_name, "bu") ~ "bu",
      str_detect(par_name, "by") ~ "by",
      TRUE ~ par_name
    ),
    par_name = factor(par_name,
                      levels = c("b00","b0", "b11" ,"a11","bu","by",
                                 "lambda","tau","eta"))
  ) %>%
  group_by(lvmodel, samplesize, nitem, par_name, rep) %>%
  summarise(
    err = mean(value),
    rerr = mean(rvalue),

    bias = mean(value),
    rbias = mean(rvalue),

    X2.5. = mean(X2.5.),
    X97.5. = mean(X97.5.),
    coverage = mean(coverage)
  ) %>%
  mutate(
    abserr = abs(err),
    absrerr = abs(rerr),

    absbias = abs(err),
    absrbias = abs(rerr)
    ) %>%
  mutate_if(is.numeric, ~ round(.x, 3))


total_res2 <- total_res1 %>%
  group_by(lvmodel, samplesize, nitem, par_name) %>%
  summarise(
    N = n(),
    bias = mean(err),
    absbias = mean(abs(err)),

    rbias = mean(rerr),
    absrbias = mean(abs(rerr)),

    rmse = sqrt(mean(err^2)),
    absrmse = sqrt(mean(abs(err)^2)),

    absrrmse = sqrt(mean(rerr^2)),
    absrrmse = sqrt(mean(abs(rerr)^2)),

    VAR.bias = var(err),

    X2.5. = mean(X2.5.),
    X97.5. = mean(X97.5.),
    coverage = mean(coverage)
  ) %>%
  ungroup() %>%
  mutate(
    MSE.bias = bias^2
  ) %>%
  arrange(lvmodel, nitem, par_name, samplesize)

yvalue <- "absbias"

total_res1 %>%
  filter(lvmodel == "rasch") %>%
  filter(nitem == "100") %>%
  ggplot(aes_string(x = "par_name", y = yvalue)) +
  geom_violin(
    trim=F,
    fill = "skyblue", alpha = 0.5, color = NA) +
  geom_sina(
    position = position_jitter(width = 0.05),
    alpha = 0.2) +
  # geom_hline(yintercept = 0) +
  geom_point(data =
               total_res2 %>%
               filter(lvmodel == "rasch") %>%
               filter(nitem == "100"),
             aes_string(x = "par_name", y = yvalue),
             size = 3, shape = 24, alpha = 0.8, fill = 'red') +
  facet_grid(nitem ~  samplesize) +
  scale_y_continuous(limits = c(0, 0.3), expand = c(0,0)) +
  theme(text = element_text(size = 40))

total_res2 %>%
  filter(lvmodel == "rasch") %>%
  filter(nitem == "100") %>%
  ggplot(aes_string(x = "par_name", y = yvalue)) +
  geom_col(fill = "grey50", color = "white") +
  facet_grid(nitem ~  samplesize) +
  theme(text = element_text(size = 40))

total_res2 %>%
  filter(lvmodel == "rasch") %>%
  filter(nitem == "100") %>%
  ggplot(aes_string(x = "par_name", y = yvalue)) +
  geom_point(shape = 21, color = 'black',
             fill = 'white', size = 3, stroke = 3) +
  facet_grid(nitem ~  samplesize) +
  theme(text = element_text(size = 40))


p_ni100 <- total_res2 %>%
  filter(lvmodel == "rasch") %>%
  filter(nitem == "100") %>%
  ggplot(aes_string(x = "par_name", y = yvalue)) +
  geom_col(fill = "grey50", color = "white") +
  facet_grid(nitem ~  samplesize) +
  theme_half_open(font_size = 30) +
  panel_border()

p_ss1000 <- total_res2 %>%
  filter(lvmodel == "rasch") %>%
  filter(samplesize == "1000") %>%

  ggplot(aes_string(x = "par_name", y = yvalue)) +
  geom_col(fill = "grey50", color = "white") +
  facet_grid(samplesize ~ nitem ) +
  theme_half_open(font_size = 30) +
  # theme_minimal_hgrid(12) +
  panel_border()


title <- ggdraw() +
  draw_label(
    "FLPS results with Rasch model",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 3)
  )

# theme_half_open(11, rel_small = 1) +
# panel_border()  # always place this after the theme
ggpubr::ggarrange(p_ni100, p_ss1000, ncol = 1)

# plot_row <- plot_grid(
#   p_ni100, p_ss1000,
#   align = "v",
#   ncol = 1, axis = 'l',
#   labels = "AUTO",
#   label_size = 12,
#   label_x = 0, label_y = 1,
#   hjust = -0.5, vjust = 1.0)


# plot_grid(
#   title, plot_row,
#   ncol = 1,
#   # rel_heights values control vertical title margins
#   rel_heights = c(0.1, 1)
# )
```

