---
title: "simulation"
author: ""
date: '`r Sys.Date()`'
output:
  html_document:
    highlight: py
    css: "style.css"
    code_folding: show
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options:
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  eval = T,
  echo = F,
  fig.height = 14,
  fig.width = 24,
  out.width = '100%',
  warning = FALSE,
  message = F,
  include = T
)
library(rstan); library(tidyverse); library(knitr);library(ggforce)

base_path <- rprojroot::find_rstudio_root_file()
source_path <- file.path(base_path, "R")

report_path <- file.path(base_path, "report")
rds_path <- file.path(report_path, "rds")
fig_path <- file.path(report_path, "figure")

theme_set(theme_bw(base_size = 32))

res00 <- readRDS(file.path(base_path,"test/test_mplus/0621_mplus_res.rds"))

res01 <- res00 %>%
  mutate(
    paramHeader = case_when(
      str_detect(paramHeader, "F1.BY") ~ "lambda",
      str_detect(paramHeader, "Thresholds") ~ "tau",
      TRUE ~ paramHeader
    ),
    param =
      case_when(
        str_detect(param, "ITEM[0-9]+$") ~ paramHeader,
        str_detect(param, "ITEM[0-9]+\\$1") ~ paramHeader,

        TRUE ~ paste0(paramHeader,param)
      )


  ) %>%

  separate(condition, c("lvmodel", "samplesize","nitem","rep"),
           sep = "_") %>%

  # filter(!str_detect(param, "Y\\.ONX")) %>%

  rename("par_name" = "param") %>%

  mutate(err = est - true_param) %>%
  mutate(
    par_name =
      case_when(
        par_name == "F1.ONX1" ~ "bu11",
        par_name == "F1.ONX2" ~ "bu12",
        par_name == "Y.ONF1" ~ "a11",
        par_name == "Y.ONF1Z" ~ "b11",
        par_name == "Y.ONZ" ~ "b0",
        par_name == "Y.ONX1" ~ "by1",
        par_name == "Y.ONX2" ~ "by2",
        TRUE ~ par_name
      ),
    par_name = factor(
      par_name,
      levels = c("bu11","bu12","a11", "b11", "b0", "by1", "by2", "lambda","tau")
    )
  ) %>% 
  mutate(samplesize =
           factor(samplesize, levels = c(100, 500, 1000)),
         nitem =
           factor(nitem, levels = c(10, 50, 100))
         ) %>% 
  group_by(par_name, samplesize, nitem, rep) %>%
  summarise(
    err = mean(err)
  )


res02 <- res01 %>% 
  group_by(par_name, samplesize, nitem) %>% 
  summarise(
    bias = mean(err)
  )

```



## Results based on Mplus

### Sample size = 100 {.tabset}

#### Range -1 ~ 1

```{r}
res01 %>%
  filter(samplesize == 100) %>%
  ggplot(aes(x = par_name, y = err)) +
  geom_violin(
    trim=F,
    fill = "skyblue", alpha = 0.6, color = NA) +
  ggforce::geom_sina(size = 4,
                     alpha = 1
  ) +
  geom_hline(yintercept = 0) +
  geom_point(
    data = res02 %>% filter(samplesize == 100),
    aes(x = par_name, y = bias),
    size = 6,
    shape = 24,
    alpha = 0.8,
    fill = "red"
  ) +
  # stat_summary(
  #   geom = "point",
  #   fun = "mean",
  #   col = "black",
  #   size = 6,
  #   shape = 24,
  #   alpha = 0.8,
  #   fill = "red"
  # ) +
  facet_grid(samplesize ~ nitem) +
  scale_y_continuous(n.breaks = 10,
                     limits = c(-1, 1))
```

#### Range -10 ~ 10

```{r}
res01 %>%
  filter(samplesize == 100) %>%
  ggplot(aes(x = par_name, y = err)) +
  geom_violin(
    trim=F,
    fill = "skyblue", alpha = 0.6, color = NA) +
  ggforce::geom_sina(size = 4,
                     alpha = 1
  ) +
  geom_hline(yintercept = 0) +
  geom_point(
    data = res02 %>% filter(samplesize == 100),
    aes(x = par_name, y = bias),
    size = 6,
    shape = 24,
    alpha = 0.8,
    fill = "red"
  ) +
  # stat_summary(
  #   geom = "point",
  #   fun = "mean",
  #   col = "black",
  #   size = 6,
  #   shape = 24,
  #   alpha = 0.8,
  #   fill = "red"
  # ) +
  facet_grid(samplesize ~ nitem) +
  scale_y_continuous(n.breaks = 10,
                     limits = c(-10, 10))
```


### Sample size = 500

```{r}
res01 %>%
  filter(samplesize == 500) %>%
  ggplot(aes(x = par_name, y = err)) +
  geom_violin(
    trim=F,
    fill = "skyblue", alpha = 0.6, color = NA) +
  ggforce::geom_sina(size = 4,
                     alpha = 1
  ) +
  geom_hline(yintercept = 0) +
  geom_point(
    data = res02 %>% filter(samplesize == 500),
    aes(x = par_name, y = bias),
    size = 6,
    shape = 24,
    alpha = 0.8,
    fill = "red"
  ) +
  facet_grid(samplesize ~ nitem) +
  scale_y_continuous(n.breaks = 10,
                     limits = c(-1, 1))
```

### Sample size = 1000

```{r}
res01 %>%
  filter(samplesize == 1000) %>%
  ggplot(aes(x = par_name, y = err)) +
  geom_violin(
    trim=F,
    fill = "skyblue", alpha = 0.6, color = NA) +
  ggforce::geom_sina(size = 4,
                     alpha = 1
  ) +
  geom_hline(yintercept = 0) +
  geom_point(
    data = res02 %>% filter(samplesize == 1000),
    aes(x = par_name, y = bias),
    size = 6,
    shape = 24,
    alpha = 0.8,
    fill = "red"
  ) +
  facet_grid(samplesize ~ nitem) +
  scale_y_continuous(n.breaks = 10,
                     limits = c(-1, 1))
```


## Results table

```{r, include=FALSE}
source(file.path(base_path,"test/paper_materials/table_function.r"), 
       local = knitr::knit_global())

```

```{r}
library(gt)

total_res <- readRDS(file.path(base_path,"test/shinydata/0608_data.rds"))
mpart <- readRDS(file.path(base_path,"test/shinydata/0608_mpart.rds")) %>% 
  rename(est_mean = mean)

mpart0 <- mpart %>%
  mutate(
    par_name0 = case_when(
      str_detect(par_name, "eta") ~ "eta",
      str_detect(par_name, "lambda") ~ "lambda",
      str_detect(par_name, "tau") ~ "tau"
    ),

    err = est_mean - true_param,

    coverage =
      case_when(
        true_param > X2.5. & true_param < X97.5. ~ 1,
        TRUE ~ 0
      ),

    converge_Rhat =
      case_when(
        Rhat > 1.1  ~ 0,
        TRUE ~ 1
      )

  ) %>%
  separate(
    cond, c("lvmodel","samplesize","nitem","z1","z2","z3","z4","rep"),
    sep = "_"
  ) %>%
  select(-starts_with("z")) %>%
  select(lvmodel, samplesize, nitem, rep, par_name, par_name0,
         true_param, est_mean,
         n_eff,
         Rhat,
         err,
         coverage,
         converge_Rhat)

xxxx <- mpart0 %>%
  distinct(lvmodel,samplesize, nitem, rep)
trt <- c()
for(i in 1:nrow(xxxx)) {
  ss <- xxxx[i,] %>% pull(samplesize) %>% as.numeric()
  ni <- xxxx[i,] %>% pull(nitem) %>% as.numeric()
  lv <- xxxx[i,] %>% pull(lvmodel)

  if(lv == "rasch") {
    trt <- c(trt, c(rep(c("1","0"), each = ss/2),
                    rep(c(""), each = ni)))
  } else if(lv %in% c("gpcm","grm")) {
    trt <- c(trt, c(rep(c("1","0"), each = ss/2),
                    rep(c("","","",""), each = ni)))

  } else {
    trt <- c(trt, c(rep(c("1","0"), each = ss/2),
                    rep(c("",""), each = ni)))
  }
}
# length(trt)
mpart0$trt <- trt

mpart_by_rep <- mpart0 %>%
  filter(!is.nan(Rhat)) %>%
  mutate(par_name0 = paste0(par_name0, trt)) %>%
  group_by(lvmodel, samplesize, nitem, rep, par_name0) %>%
  summarise(
    absbias = mean(abs(err)),
    rmse = mean(err^2),
    coverage = mean(coverage),
    Rhatconv = mean(converge_Rhat),
    Rhatmean = mean(Rhat)
  )

mpart_by_cond <- mpart_by_rep %>%
  group_by(lvmodel, samplesize, nitem, par_name0) %>%
  summarise(
    absbias = mean(absbias),
    rmse = mean(rmse),
    coverage = mean(coverage),
    Rhatconv = mean(Rhatconv),
    Rhatmean = mean(Rhatmean)
  )

mpart_by_cond <- mpart_by_cond %>%
  mutate(
    lvmodel = case_when(
      lvmodel == "rasch" ~ "Rasch",
      lvmodel == "2pl" ~ "2PL",
      lvmodel == "gpcm" ~ "GPCM",
      lvmodel == "grm" ~ "GRM"
    ),
    lvmodel = factor(lvmodel,
                     c("Rasch","2PL","GRM","GPCM")),

    par_name0 = case_when(
      par_name0 == "eta1" ~ "theta1",
      par_name0 == "eta0" ~ "theta0",
      par_name0 == "lambda" ~ "a",
      par_name0 == "tau" ~ "b"
    ),
    par_name0 = factor(par_name0,
                     c("theta1","theta0","a","b")),

    samplesize = factor(samplesize, c("500","1000","2000")),
    nitem = factor(nitem, c("50","100","200"))
  ) %>%
  ungroup() %>%
  mutate_if(is.numeric, ~ round(.x, 3))


# Structure model
total_res1 <-
  total_res %>%
  mutate(
    par_name = as.character(par_name),
    par_name = case_when(
      str_detect(par_name, "bu") ~ "bu",
      str_detect(par_name, "by") ~ "by",
      TRUE ~ par_name
    ),
    par_name = factor(par_name,
                      levels = c("b00","b0", "b11" ,"a11","bu","by",
                                 "lambda","tau","eta"))
  ) %>%
  filter(!par_name %in% c("lambda","tau","eta")) %>%
  group_by(lvmodel, samplesize, nitem, par_name, rep) %>%
  summarise(
    err = mean(value),
    rerr = mean(rvalue),

    bias = mean(value),
    rbias = mean(rvalue),

    X2.5. = mean(X2.5.),
    X97.5. = mean(X97.5.),
    coverage = mean(coverage)
  ) %>%
  mutate(
    abserr = abs(err),
    absrerr = abs(rerr),

    absbias = abs(err),
    absrbias = abs(rerr)
    ) %>%
  mutate_if(is.numeric, ~ round(.x, 3))


total_res2 <- total_res1 %>%
  group_by(lvmodel, samplesize, nitem, par_name) %>%
  summarise(
    N = n(),
    bias = mean(err),
    absbias = mean(abs(err)),

    rbias = mean(rerr),
    absrbias = mean(abs(rerr)),

    rmse = sqrt(mean(err^2)),
    absrmse = sqrt(mean(abs(err)^2)),

    absrrmse = sqrt(mean(rerr^2)),
    absrrmse = sqrt(mean(abs(rerr)^2)),

    VAR.bias = var(err),

    X2.5. = mean(X2.5.),
    X97.5. = mean(X97.5.),
    coverage = mean(coverage)
  ) %>%
  ungroup() %>%
  mutate(
    MSE.bias = bias^2
  ) %>%
  arrange(lvmodel, nitem, par_name, samplesize)

total_res3 <- total_res2 %>%
  mutate(
    lvmodel = case_when(
      lvmodel == "rasch" ~ "Rasch",
      lvmodel == "2pl" ~ "2PL",
      lvmodel == "gpcm" ~ "GPCM",
      lvmodel == "grm" ~ "GRM"
    ),
    lvmodel = factor(lvmodel,
                     c("Rasch","2PL","GRM","GPCM")),

    samplesize = factor(samplesize, c("500","1000","2000")),
    nitem = factor(nitem, c("50","100","200"))
  ) %>%
  ungroup() %>%
  mutate_if(is.numeric, ~ round(.x, 3))


# Table ---------------------------------------------------------
```

### Measurement part by sample
```{r}

mpart_by_cond %>%
  filter(nitem == "100") %>%
  select(-absbias, -Rhatconv, -nitem) %>%
  mutate_if(is.numeric, ~ format(.x, nsmall = 3)) %>%
  mutate_if(is.numeric, as.character) %>%
  pivot_wider(names_from = c(par_name0),
              values_from = c(rmse, coverage, Rhatmean),
              values_fill = " ") %>%
  arrange(lvmodel, samplesize) %>%
  mpart_t_sample()
```

### Measurement part by nitem

```{r}
## by nitem
mpart_by_cond %>%
  filter(samplesize == "1000") %>%
  select(-absbias, -Rhatconv, -samplesize) %>%
  mutate_if(is.numeric, ~ format(.x, nsmall = 3)) %>%
  mutate_if(is.numeric, as.character) %>%
  pivot_wider(names_from = c(par_name0),
              values_from = c(rmse, coverage, Rhatmean),
              values_fill = " ") %>%
  arrange(lvmodel, nitem) %>%
  mpart_t_nitem()
```

### Structure part by sample

```{r}
total_res3 %>%
  filter(nitem == "100") %>%
  filter(!par_name %in% c("b00","bu","by")) %>%
  select(lvmodel, samplesize, par_name, rmse, coverage) %>%
  mutate_if(is.numeric, ~ format(.x, nsmall = 3)) %>%
  mutate_if(is.numeric, as.character) %>%
  pivot_wider(names_from = c(par_name),
              values_from = c(rmse, coverage),
              values_fill = " ") %>%
  struc_t_sample()
```

### Structure part by nitem

```{r}
total_res3 %>%
  filter(samplesize == "1000") %>%
  filter(!par_name %in% c("b00","bu","by")) %>%
  select(lvmodel, nitem, par_name, rmse, coverage) %>%
  mutate_if(is.numeric, ~ format(.x, nsmall = 3)) %>%
  mutate_if(is.numeric, as.character) %>%
  pivot_wider(names_from = c(par_name),
              values_from = c(rmse, coverage),
              values_fill = " ") %>%
  struc_t_nitem()
```


