---
title: "Simulation Report"
author: ""
date: '`r Sys.Date()`'
output:
  html_document:
    css: "style.css"
    code_folding: show
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: false
editor_options:
  chunk_output_type: console
---

```{r library, message = FALSE, results = 'hide', echo = FALSE}
# Suppress summarise info
options(dplyr.summarise.inform = FALSE)

knitr::opts_chunk$set(echo = FALSE)
library(kableExtra)
library(tidyverse)
library(knitr)
library(ggpubr); 
library(ggrepel)

root <- rprojroot::find_rstudio_root_file()
report_path <- file.path(root)

res_irt <- readRDS(file.path(report_path, "test/test_scaling/twopl_result.rds"))
res_cfa <- readRDS(file.path(report_path, "test/test_scaling/cfa_result.rds"))
```


## Latent variable models

- IRT: $P(y_{ij} = 1 | \eta_i) = \frac{exp(a_j(\eta_i - b_j))}{1 + exp(a_j(\eta_i - b_j))}$

- SEM:  $P(y_{ij} = 1 | \eta_i) = \frac{exp(intercept_j + a_j*\eta_i))}{1 + exp(intercept_j + a_j*\eta_i))}$

- CFA: $y_{ij} = \lambda_j\eta_i + \epsilon_{ij}$


## CFA

### stan code



```{r}
stan_model <- paste(read_lines(file.path(report_path, "test/test_scaling/stan/CFA.stan")), collapse = "\n")
cat(stan_model)
```


### results

```{r}
fit <- res_cfa$cfa.fit

est <- colMeans(fit[str_detect(names(fit), "lambda1")])
est0 <- colMeans(fit[str_detect(names(fit), "lambda")])[1:10]
cbind(pop = res_cfa$sim_dt_cfa$lv.par, 
      est = est, 
      est_noncont = est0) %>% 
  data.frame(row.names = 1:10) %>% 
  set_names(c("pop_lambda", "est_lambda", "est_nonconst")) %>% 
  mutate_all(round, 3)

eta <- cbind(est_eta = colMeans(fit[str_detect(names(fit), "eta")]), pop_eta = res_cfa$sim_dt_cfa$true_eta)

# Mean of ability
round(colMeans(eta ), 3) 
# SD of ability
round(apply(eta, 2, sd), 3)

plot(eta[,"est_eta"],eta[,"pop_eta"])
```


## IRT

### stan code {.tabset}

#### This works

```{r}
stan_model <- paste(read_lines(file.path(report_path,"test/test_scaling/stan/IRT_4.stan")), collapse = "\n")
cat(stan_model)
```

#### This din't work

```{r}
stan_model <- paste(read_lines(file.path(report_path,"test/test_scaling/stan/IRT.stan")), collapse = "\n")
cat(stan_model)
```

### results

```{r}

fit <- res_irt$twopl.fit
est_disc <- colMeans(fit[str_detect(names(fit), pattern = "disc1")])
est_diff0 <- colMeans(fit[str_detect(names(fit), "diff1")])
est_diff1 <- colMeans(fit[str_detect(names(fit), "difficulty")])

cbind(pop_disc = res_irt$sim_dt_2pl$lv.par[,1],
      est_disc = est_disc,
      pop_diff = res_irt$sim_dt_2pl$lv.par[,2],
      est_diff = est_diff1,
      est_int = est_diff0) %>% 
  data.frame(row.names = 1:10) %>% 
  set_names(c("pop_disc", "est_disc", "pop_diff", "est_diff", "est_intercept")) %>% mutate_all(round, 3)

eta <- cbind(est_eta = colMeans(fit[str_detect(names(fit), "eta")]), pop_eta = res_irt$sim_dt_2pl$true_eta)

# Mean of ability
round(colMeans(eta ), 3) 
# SD of ability
round(apply(eta, 2, sd), 3)

plot(eta[,"est_eta"],eta[,"pop_eta"])
```







